In [1]:
import pandas as pd
import datetime
from geopy.distance import vincenty

In [2]:
# Read in data with proper titles
df = pd.read_csv("January_Bus_8_to_10.csv", low_memory = False)
# df.columns = ["TimeStamp", "LineId", "JourneyPatternId", "TimeFrame", "VehicleJourneyId", "Congestion", "Long", "Lat", "Delay", "BlockId", "StopId"]

In [3]:
df.head()

,TimeStamp,LineId,JourneyPatternId,TimeFrame,VehicleJourneyId,Congestion,Long,Lat,Delay,BlockId,StopId,weekday
0,2012-11-08 00:00:07,102,01021001,2012-11-07,435,0,-6.212934,53.409649,-443,102001,4381,3
1,2012-11-08 00:02:37,123,01231001,2012-11-07,5191,0,-6.325200,53.324451,294,123012,6056,3
2,2012-11-08 00:00:03,13,00130007,2012-11-07,4169,0,-6.389081,53.325191,538,13009,4663,3
3,2012-11-08 00:03:42,13,00130007,2012-11-07,4169,0,-6.401314,53.317501,546,13009,4667,3
4,2012-11-08 00:05:43,13,00130007,2012-11-07,4169,0,-6.412405,53.324871,491,13009,2136,3

In [4]:
df.shape

(387172, 12)

In [5]:
df['TimeStamp'] =  pd.to_datetime(df['TimeStamp'], format='%Y-%m-%d %H:%M:%S')
df["LineId"] = df["LineId"].astype("category")
df["JourneyPatternId"] = df["JourneyPatternId"].astype("category")
df["TimeFrame"] = df["TimeFrame"].astype("category")
df["VehicleJourneyId"] = df["VehicleJourneyId"].astype("category")
df["Congestion"] = df["Congestion"].astype("category")
df["BlockId"] = df["BlockId"].astype("category")
df["StopId"] = df["StopId"].astype("category")

In [6]:
df.dtypes

TimeStamp           datetime64[ns]
LineId                    category
JourneyPatternId          category
TimeFrame                 category
VehicleJourneyId          category
Congestion                category
Long                       float64
Lat                        float64
Delay                        int64
BlockId                   category
StopId                    category
weekday                      int64
dtype: object

In [7]:
# Organise the Data
df = df.sort_values(['TimeFrame', 'LineId', 'JourneyPatternId', 'VehicleJourneyId', 'TimeStamp'], ascending=True)

In [8]:
# Clean up index
df = df.reset_index()
del df['index']

In [9]:
df['weekday'] = df['TimeStamp'].dt.dayofweek

In [10]:
df["JourneyPatternId"].value_counts().count()

461

In [11]:
df.head(10)

,TimeStamp,LineId,JourneyPatternId,TimeFrame,VehicleJourneyId,Congestion,Long,Lat,Delay,BlockId,StopId,weekday
0,2012-11-08 00:01:38,4,00040001,2012-11-07,5331,0,-6.153467,53.288651,453,4001,7226,3
1,2012-11-08 00:00:07,4,00041002,2012-11-07,5416,0,-6.265067,53.388851,-23,4012,281,3
2,2012-11-08 00:00:09,7,00070001,2012-11-07,6963,0,-6.135499,53.292816,-113,7014,2040,3
3,2012-11-08 00:03:30,7,00070001,2012-11-07,6963,0,-6.142740,53.292503,0,7014,2043,3
4,2012-11-08 00:08:50,7,00070001,2012-11-07,6963,0,-6.139555,53.273537,-6,7014,3210,3
5,2012-11-08 00:09:48,7,00070001,2012-11-07,6963,0,-6.138042,53.271317,-24,7014,3211,3
6,2012-11-08 00:12:10,7,00070001,2012-11-07,6963,0,-6.139968,53.269024,55,7014,3212,3
7,2012-11-08 00:14:25,7,00070001,2012-11-07,6963,0,-6.137609,53.262070,22,7014,3215,3
8,2012-11-08 00:01:38,7,00070001,2012-11-07,6966,0,-6.129867,53.248032,-83,7009,4982,3
9,2012-11-08 00:00:09,7,00071001,2012-11-07,6855,0,-6.233802,53.330879,2527,7001,487,3

## Now Add The Distance, Destination Stop, Time Taken

In [12]:
def get_distance(lat1, long1, lat2, long2):
    """ Get distance between two geo coordinates """
    
    stop1 = (lat1, long1)
    stop2 = (lat2, long2)
    
    return vincenty(stop1, stop2).meters

In [14]:
# List to hold features
travel_time = list()
distance = list()

for item, row in df.iterrows():
    
    # Set up values on first iteration
    if item == 0:
        last_lat = row[7]
        last_long = row[6]
        last_id = row[4]
        
        start_time = row[0]
        last_distance = 0
        
        travel_time.append(0.0)
        distance.append(0)
        continue
    
    current_id = row[4]
    current_lat = row[7]
    current_long = row[6]
    current_time = row[0]
    current_distance = get_distance(current_lat, current_long, last_lat, last_long)
    
    # If it's a new Journey ID
    if current_id != last_id:
        last_id = row[4]
        last_lat = row[7]
        last_long = row[6]
        
        start_time = row[0]
        last_distance = 0
        
        travel_time.append(0.0)
        distance.append(0)
        continue
        
    travel_time.append(abs((start_time - current_time).total_seconds()))
    
    current_distance = get_distance(current_lat, current_long, last_lat, last_long)
        
    distance.append(last_distance + current_distance)
    
    last_distance = distance[-1]
    last_time = row[0]
    last_lat = row[7]
    last_long = row[6]
    last_id = row[4]

In [15]:
len(travel_time)

387172

In [16]:
len(distance)

387172

In [17]:
df.shape

(387172, 12)

In [20]:
df["TravelTime"] = travel_time

In [21]:
df["Distance"] = distance

In [23]:
# Clean up index
df = df.reset_index()
del df['index']

In [1]:
df

NameError: name 'df' is not defined

In [27]:
# Organise the Data
df = df.sort_values(['TimeFrame', 'LineId', 'JourneyPatternId', 'VehicleJourneyId', 'TimeStamp'], ascending=True)

In [30]:
test = df[df.VehicleJourneyId == 146]

In [31]:
test

,TimeStamp,LineId,JourneyPatternId,TimeFrame,VehicleJourneyId,Congestion,Long,Lat,Delay,BlockId,StopId,weekday,TravelTime,Distance
79203,2012-11-08 17:17:10,41,00410001,2012-11-08,146,0,-6.254150,53.350376,185,41002,1171,3,0.0,0.000000
79204,2012-11-08 17:19:48,41,00410001,2012-11-08,146,0,-6.256622,53.353806,208,41002,1173,3,158.0,415.713536
79205,2012-11-08 17:21:10,41,00410001,2012-11-08,146,0,-6.258642,53.356350,186,41002,1174,3,240.0,729.166802
79206,2012-11-08 17:24:28,41,00410001,2012-11-08,146,0,-6.260883,53.360165,193,41002,15,3,438.0,1179.203514
79207,2012-11-08 17:27:47,41,00410001,2012-11-08,146,0,-6.258309,53.362984,272,41002,17,3,637.0,1536.688322
79208,2012-11-08 17:36:21,41,00410001,2012-11-08,146,0,-6.249843,53.376286,369,41002,203,3,1151.0,3120.734564
79209,2012-11-08 17:37:20,41,00410001,2012-11-08,146,0,-6.246595,53.379551,369,41002,204,3,1210.0,3543.536997
79210,2012-11-08 17:38:22,41,00410001,2012-11-08,146,0,-6.245199,53.381317,369,41002,205,3,1272.0,3760.929708
79211,2012-11-08 17:40:04,41,00410001,2012-11-08,146,0,-6.244052,53.383217,419,41002,1620,3,1374.0,3985.740150
79212,2012-11-08 17:41:20,41,00410001,2012-11-08,146,0,-6.244926,53.387997,378,41002,220,3,1450.0,4520.892265
79213,2012-11-08 17:43:04,41,00410001,2012-11-08,146,0,-6.246352,53.390049,404,41002,1622,3,1554.0,4768.189926
79214,2012-11-08 17:43:42,41,00410001,2012-11-08,146,0,-6.246200,53.391926,404,41002,1623,3,1592.0,4977.332665
79215,2012-11-08 17:46:24,41,00410001,2012-11-08,146,0,-6.245337,53.396049,436,41002,1624,3,1754.0,5439.773992
79216,2012-11-08 17:51:27,41,00410001,2012-11-08,146,0,-6.240226,53.404087,540,41002,1626,3,2057.0,6396.771351
79217,2012-11-08 18:10:00,41,00410001,2012-11-08,146,0,-6.218293,53.454853,267,41002,4330,3,3170.0,12231.796608
79218,2012-11-08 18:13:34,41,00410001,2012-11-08,146,0,-6.220099,53.458893,392,41002,3679,3,3384.0,12697.156758
79219,2012-11-08 18:17:52,41,00410001,2012-11-08,146,0,-6.234144,53.463959,442,41002,3864,3,3642.0,13787.165214
79220,2012-11-08 18:18:37,41,00410001,2012-11-08,146,0,-6.237309,53.465862,442,41002,3865,3,3687.0,14085.562284
79221,2012-11-08 18:22:33,41,00410001,2012-11-08,146,0,-6.245102,53.459915,556,41002,4915,3,3923.0,14925.782696
80161,2012-11-08 17:07:50,41,00411001,2012-11-08,146,0,-6.255784,53.349068,0,41002,288,3,0.0,0.000000
223756,2012-11-09 17:15:46,41,00410001,2012-11-09,146,0,-6.254150,53.350376,93,41002,1171,4,0.0,0.000000
223757,2012-11-09 17:17:47,41,00410001,2012-11-09,146,0,-6.255172,53.351791,174,41002,1172,4,121.0,171.555919
223758,2012-11-09 17:20:08,41,00410001,2012-11-09,146,0,-6.258642,53.356350,123,41002,1174,4,262.0,729.073434
223759,2012-11-09 17:23:47,41,00410001,2012-11-09,146,0,-6.260883,53.360165,157,41002,15,4,481.0,1179.110147
223760,2012-11-09 17:26:30,41,00410001,2012-11-09,146,0,-6.258309,53.362984,194,41002,17,4,644.0,1536.594954
223761,2012-11-09 17:37:16,41,00410001,2012-11-09,146,0,-6.251790,53.373863,504,41002,85,4,1290.0,2822.765338
223762,2012-11-09 17:41:37,41,00410001,2012-11-09,146,0,-6.245199,53.381317,559,41002,205,4,1551.0,3761.169116
223763,2012-11-09 17:42:33,41,00410001,2012-11-09,146,0,-6.244052,53.383217,570,41002,1620,4,1607.0,3985.979558
223764,2012-11-09 17:44:15,41,00410001,2012-11-09,146,0,-6.244926,53.387997,551,41002,220,4,1709.0,4521.131673
223765,2012-11-09 17:46:19,41,00410001,2012-11-09,146,0,-6.246200,53.391926,549,41002,1623,4,1833.0,4966.543357
223766,2012-11-09 17:47:34,41,00410001,2012-11-09,146,0,-6.245337,53.396049,524,41002,1624,4,1908.0,5428.984684
223767,2012-11-09 17:49:13,41,00410001,2012-11-09,146,0,-6.243242,53.401035,491,41002,1625,4,2007.0,6001.125727
223768,2012-11-09 17:50:15,41,00410001,2012-11-09,146,0,-6.240226,53.404087,471,41002,1626,4,2069.0,6395.605429
223769,2012-11-09 17:55:05,41,00410001,2012-11-09,146,0,-6.231809,53.421616,384,41002,1630,4,2359.0,8425.176101
223770,2012-11-09 17:59:40,41,00410001,2012-11-09,146,0,-6.241761,53.427517,451,41002,7348,4,2634.0,9357.378403
223771,2012-11-09 18:02:12,41,00410001,2012-11-09,146,0,-6.230061,53.429401,431,41002,3671,4,2786.0,10162.855738
223772,2012-11-09 18:09:13,41,00410001,2012-11-09,146,0,-6.215951,53.453133,282,41002,5074,4,3207.0,12965.585247
223773,2012-11-09 18:11:34,41,00410001,2012-11-09,146,0,-6.218293,53.454853,349,41002,4330,4,3348.0,13212.262760
223774,2012-11-09 18:19:36,41,00410001,2012-11-09,146,0,-6.220099,53.458893,742,41002,3679,4,3830.0,13677.622910
223775,2012-11-09 18:22:14,41,00410001,2012-11-09,146,0,-6.223548,53.459705,853,41002,5075,4,3988.0,13923.894958
223776,2012-11-09 18:24:35,41,00410001,2012-11-09,146,0,-6.231205,53.462120,870,41002,3682,4,4129.0,14499.128209
223777,2012-11-09 18:25:14,41,00410001,2012-11-09,146,0,-6.234144,53.463959,870,41002,3864,4,4168.0,14781.958523
223778,2012-11-09 18:26:14,41,00410001,2012-11-09,146,0,-6.237309,53.465862,911,41002,3865,4,4228.0,15080.355593
223779,2012-11-09 18:27:15,41,00410001,2012-11-09,146,0,-6.239457,53.464035,911,41002,4912,4,4289.0,15328.743346
223780,2012-11-09 18:28:14,41,00410001,2012-11-09,146,0,-6.241820,53.459888,929,41002,4914,4,4348.0,15816.238571
223781,2012-11-09 18:29:18,41,00410001,2012-11-09,146,0,-6.245102,53.459915,945,41002,4915,4,4412.0,16034.255136
224669,2012-11-09 17:13:26,41,00411001,2012-11-09,146,0,-6.256550,53.348915,24,41002,288,4,0.0,0.000000

In [ ]:
df.to_csv("3_days_cleaned_sprint_2.csv")