In [27]:
import pandas as pd
from ipykernel import kernelapp as app

In [28]:
df = pd.read_csv("sprint1_test.csv", low_memory=False)

In [29]:
df.head()

,TimeStamp,LineId,JourneyPatternId,VehicleJourneyId,StopId,Address,Rain
0,2012-11-06 00:00:02,41,041B0002,61,3874,Rolestown,0.0
1,2012-11-06 00:00:02,27,00270001,4976,2355,Fortunestown Rd,0.0
2,2012-11-06 00:00:02,140,01400001,6615,895,Rathmines Road,0.0
3,2012-11-06 00:00:02,83,083A0001,7099,324,Harristown,0.0
4,2012-11-06 00:00:02,16,016C0001,6175,270,O'Connell St,0.0

In [30]:
# df = df[df.LineId == '46A']
# df = df[df.LineId == 41]
df.shape

(142734, 7)

In [31]:
# test = df[df.LineId == 145]
# test["VehicleJourneyId"].value_counts()
# test = df[df.VehicleJourneyId == 6652]
# test['TimeStamp'] =  pd.to_datetime(test['TimeStamp'], format='%Y-%m-%d %H:%M:%S')
# df.groupby('VehicleJourneyId').StopId.unique()
# df2 = df.drop_duplicates(["VehicleJourneyId", "StopId"])

In [32]:
# Organise the Data in order of each journey and the time broadcast
df = df.sort_values(['VehicleJourneyId', 'TimeStamp'], ascending=True)

#### Use this as a test later

In [33]:
# Test to see journey times at diffent times

# temp = df[df.LineId == 331]
# temp = temp[temp.StopId == 3567]
# temp

## Remove Journey's with only 1 stop

In [34]:
# # df[df.VehicleJourneyId.count() != 1]
# # uniq_b = df.VehicleJourneyId.unique()
# # uniq_b
# # df['VehicleJourneyId'].value_counts() > 1


# """ This takes a while """

# vc = df['VehicleJourneyId'].value_counts()
# u  = [i not in set(vc[vc==1].index) for i in df['VehicleJourneyId']]
# df = df[u]

In [35]:
# Clean up index
df = df.reset_index()
del df['index']

# Must Now Add Destination Stop ID & Time to Travel There

In [36]:
df

,TimeStamp,LineId,JourneyPatternId,VehicleJourneyId,StopId,Address,Rain
0,2012-11-06 16:17:54,331,033A1002,1,3567,Town Parks Rd,0.0
1,2012-11-06 16:19:36,331,033A1002,1,7292,Thomas Hand St,0.0
2,2012-11-06 16:22:33,331,033A1002,1,3818,Thomas Hand St,0.0
3,2012-11-06 16:23:53,331,033A1002,1,3819,Strand Street,0.0
4,2012-11-06 16:30:15,331,033A1002,1,3829,Skerries Road,0.0
5,2012-11-06 16:33:24,331,033A1002,1,3833,Skerries Road,0.0
6,2012-11-06 16:34:23,331,033A1002,1,3834,Skerries Road,0.0
7,2012-11-06 16:35:23,331,033A1002,1,3835,Skerries Road,0.0
8,2012-11-06 16:36:23,331,033A1002,1,3836,Skerries Road,0.0
9,2012-11-06 16:42:04,331,033A1002,1,3840,Rush,0.0
10,2012-11-06 16:44:05,331,033A1002,1,3842,Whitestown Rd,0.0
11,2012-11-06 16:46:43,331,033A1002,1,3846,Whitestown Rd,0.0
12,2012-11-06 16:50:22,331,033A1002,1,3853,Station Road,0.0
13,2012-11-06 16:52:23,331,033A1002,1,3854,Station Road,0.0
14,2012-11-06 16:55:09,331,033A1002,1,3855,Station Road,0.0
15,2012-11-06 16:57:49,331,033A1002,1,3859,Lusk Road,0.0
16,2012-11-06 16:59:50,331,033A1002,1,3862,Lusk Road,0.0
17,2012-11-06 17:06:54,331,033A1002,1,3752,North Street,0.0
18,2012-11-06 17:08:14,331,033A1002,1,3689,Main Street Swords,0.0
19,2012-11-06 17:11:55,331,033A1002,1,3692,Dublin Rd,0.0
20,2012-11-06 17:22:14,331,033A0001,2,3679,Main Street Swords,0.0
21,2012-11-06 17:25:17,331,033A0001,2,3712,North Street,0.0
22,2012-11-06 17:43:50,331,033A0001,2,3768,Station Road,0.0
23,2012-11-06 17:47:31,331,033A0001,2,3775,Whitestown Rd,0.0
24,2012-11-06 17:48:30,331,033A0001,2,3777,Whitestown Rd,0.0
25,2012-11-06 17:50:14,331,033A0001,2,3778,Rush,0.0
26,2012-11-06 17:51:55,331,033A0001,2,3781,Skerries Rd Rush,0.0
27,2012-11-06 17:58:54,331,033A0001,2,3793,Skerries,0.0
28,2012-11-06 18:00:36,331,033A0001,2,3795,Holmpatrick,0.0
29,2012-11-06 18:01:37,331,033A0001,2,3797,Strand Street,0.0
...,...,...,...,...,...,...,...
142704,2012-11-06 16:04:25,31,00311001,990905,596,Howth Road,0.0
142705,2012-11-06 16:07:25,31,00311001,990905,599,Howth Road,0.0
142706,2012-11-06 16:08:45,31,00311001,990905,600,Howth Road,0.0
142707,2012-11-06 16:09:45,31,00311001,990905,601,Howth Road,0.0
142708,2012-11-06 16:17:27,31,00311001,990905,609,Howth Road,0.0
142709,2012-11-06 16:22:27,31,00311001,990905,615,Annesley Brg Rd.,0.0
142710,2012-11-06 16:26:47,31,00311001,990905,620,Talbot Street,0.0
142711,2012-11-06 09:03:33,17,00171001,996115,3082,Carysfort Avenue,0.0
142712,2012-11-06 09:05:14,17,00171001,996115,3083,Frascati Road,0.0
142713,2012-11-06 09:07:11,17,00171001,996115,431,Mount Merrion Ave,0.0
142714,2012-11-06 09:08:12,17,00171001,996115,432,Mount Merrion Ave,0.0
142715,2012-11-06 09:27:52,17,00171001,996115,876,Bird Avenue,0.0
142716,2012-11-06 09:33:51,17,00171001,996115,1315,Nutgrove Ave,0.0
142717,2012-11-06 09:37:31,17,00171001,996115,1330,Grange Road,0.0
142718,2012-11-06 09:42:12,17,00171001,996115,1086,Terenure Rd West,0.0
142719,2012-11-06 09:54:13,17,00171001,996115,3362,Sundrive Road,0.0
142720,2012-11-06 18:39:43,150,01501001,996128,1358,Dame Street,0.0
142721,2012-11-06 20:02:42,27,077A0001,999390,396,Pearse Street,0.0
142722,2012-11-06 20:04:22,27,077A0001,999390,398,Pearse Street,0.0
142723,2012-11-06 20:06:43,27,077A0001,999390,400,Pearse Street,0.0
142724,2012-11-06 20:10:03,27,077A0001,999390,4522,College Green,0.0
142725,2012-11-06 20:14:02,27,077A0001,999390,1934,Dame Street,0.0
142726,2012-11-06 20:16:03,27,077A0001,999390,2310,Werburgh Street,0.0
142727,2012-11-06 20:21:03,27,077A0001,999390,2315,Cork Street,0.0
142728,2012-11-06 20:22:02,27,077A0001,999390,2094,Cork Street,0.0
142729,2012-11-06 20:25:22,27,077A0001,999390,2095,Crumlin Road,0.0
142730,2012-11-06 20:37:02,27,077A0001,999390,5133,Tymon Park Rd,0.0
142731,2012-11-06 20:43:09,27,077A0001,999390,2616,Old Bawn Rd,0.0
142732,2012-11-06 20:47:28,27,077A0001,999390,4347,Old Blessington Rd,0.0
142733,2012-11-06 20:51:48,27,077A0001,999390,2560,Killinarden,0.0

In [37]:
stop_df = df

In [38]:
stop_df['TimeStamp'] =  pd.to_datetime(stop_df['TimeStamp'], format='%Y-%m-%d %H:%M:%S')

In [39]:
stop_df.dtypes

TimeStamp           datetime64[ns]
LineId                       int64
JourneyPatternId            object
VehicleJourneyId             int64
StopId                       int64
Address                     object
Rain                       float64
dtype: object

In [40]:
# List to hold addresses for destination addresses
dst_stop = list()
travel_time = list()

for item, row in stop_df.iterrows():
    
    # Set up values on first iteration
    if item == 0:
        last_stop = row[4]
        last_id = row[3]
        last_time = row[0]
        continue
    
    current_id = row[3]
    
    # If it's a new Journey ID
    if current_id != last_id:
        last_stop = row[4]
        last_id = row[3]
        last_time = row[0]
        df.drop(item - 1, inplace = True)
        continue
        
    dst_stop.append(row[4])
    travel_time.append(row[0] - last_time)
    last_time = row[0]

In [45]:
stop_df.shape

(135359, 7)

In [57]:
stop_df = stop_df.drop(142733)

In [58]:
stop_df.shape

(135358, 7)

In [59]:
len(dst_stop)

135358

In [60]:
len(travel_time)

135358

In [61]:
stop_df["DstStop"] = dst_stop

In [62]:
stop_df["TravelTime"] = travel_time

In [63]:
# Clean up index
stop_df = stop_df.reset_index()
del stop_df['index']

## Add Day Of Week And Modify TimeStamp

In [64]:
stop_df['weekday'] = stop_df['TimeStamp'].dt.dayofweek

In [65]:
stop_df['TimeStamp'] = stop_df['TimeStamp'].astype(str)

In [66]:
for index, row in stop_df.iterrows():
    x = row["TimeStamp"][-8:]
    stop_df.set_value(index, 'TimeStamp', x)

In [70]:
# Convert to datetime
# ad_df['TimeStamp'] =  pd.to_datetime(ad_df['TimeStamp'], format='%H:%M:%S')
stop_df['TimeStamp'] = stop_df['TimeStamp'].astype(str)
# Convert to category
# ad_df["TimeStamp"] = ad_df["TimeStamp"].astype("category")
stop_df["weekday"] = stop_df["weekday"].astype("category")

In [72]:
# Must convert travelTime into an int representing journey time in sec
import numpy as np

stop_df['TravelTime'] = stop_df['TravelTime'] / np.timedelta64(1, 's')

In [73]:
stop_df

,TimeStamp,LineId,JourneyPatternId,VehicleJourneyId,StopId,Address,Rain,DstStop,TravelTime,weekday
0,16:17:54,331,033A1002,1,3567,Town Parks Rd,0.0,7292,102.0,1
1,16:19:36,331,033A1002,1,7292,Thomas Hand St,0.0,3818,177.0,1
2,16:22:33,331,033A1002,1,3818,Thomas Hand St,0.0,3819,80.0,1
3,16:23:53,331,033A1002,1,3819,Strand Street,0.0,3829,382.0,1
4,16:30:15,331,033A1002,1,3829,Skerries Road,0.0,3833,189.0,1
5,16:33:24,331,033A1002,1,3833,Skerries Road,0.0,3834,59.0,1
6,16:34:23,331,033A1002,1,3834,Skerries Road,0.0,3835,60.0,1
7,16:35:23,331,033A1002,1,3835,Skerries Road,0.0,3836,60.0,1
8,16:36:23,331,033A1002,1,3836,Skerries Road,0.0,3840,341.0,1
9,16:42:04,331,033A1002,1,3840,Rush,0.0,3842,121.0,1
10,16:44:05,331,033A1002,1,3842,Whitestown Rd,0.0,3846,158.0,1
11,16:46:43,331,033A1002,1,3846,Whitestown Rd,0.0,3853,219.0,1
12,16:50:22,331,033A1002,1,3853,Station Road,0.0,3854,121.0,1
13,16:52:23,331,033A1002,1,3854,Station Road,0.0,3855,166.0,1
14,16:55:09,331,033A1002,1,3855,Station Road,0.0,3859,160.0,1
15,16:57:49,331,033A1002,1,3859,Lusk Road,0.0,3862,121.0,1
16,16:59:50,331,033A1002,1,3862,Lusk Road,0.0,3752,424.0,1
17,17:06:54,331,033A1002,1,3752,North Street,0.0,3689,80.0,1
18,17:08:14,331,033A1002,1,3689,Main Street Swords,0.0,3692,221.0,1
19,17:22:14,331,033A0001,2,3679,Main Street Swords,0.0,3712,183.0,1
20,17:25:17,331,033A0001,2,3712,North Street,0.0,3768,1113.0,1
21,17:43:50,331,033A0001,2,3768,Station Road,0.0,3775,221.0,1
22,17:47:31,331,033A0001,2,3775,Whitestown Rd,0.0,3777,59.0,1
23,17:48:30,331,033A0001,2,3777,Whitestown Rd,0.0,3778,104.0,1
24,17:50:14,331,033A0001,2,3778,Rush,0.0,3781,101.0,1
25,17:51:55,331,033A0001,2,3781,Skerries Rd Rush,0.0,3793,419.0,1
26,17:58:54,331,033A0001,2,3793,Skerries,0.0,3795,102.0,1
27,18:00:36,331,033A0001,2,3795,Holmpatrick,0.0,3797,61.0,1
28,18:01:37,331,033A0001,2,3797,Strand Street,0.0,6076,749.0,1
29,06:00:03,41,00411001,4,4843,Brackenstown Rd,0.0,4905,39.0,1
...,...,...,...,...,...,...,...,...,...,...
135328,08:45:51,25,025A1001,985485,347,College Street,0.0,406,140.0,1
135329,08:48:11,25,025A1001,985485,406,Nassau Street,0.0,4530,81.0,1
135330,18:22:13,4,NaN,988993,126,Ballymun Road,0.0,322,99.0,1
135331,16:01:45,31,00311001,990905,591,Dublin Rd,0.0,596,160.0,1
135332,16:04:25,31,00311001,990905,596,Howth Road,0.0,599,180.0,1
135333,16:07:25,31,00311001,990905,599,Howth Road,0.0,600,80.0,1
135334,16:08:45,31,00311001,990905,600,Howth Road,0.0,601,60.0,1
135335,16:09:45,31,00311001,990905,601,Howth Road,0.0,609,462.0,1
135336,16:17:27,31,00311001,990905,609,Howth Road,0.0,615,300.0,1
135337,16:22:27,31,00311001,990905,615,Annesley Brg Rd.,0.0,620,260.0,1
135338,09:03:33,17,00171001,996115,3082,Carysfort Avenue,0.0,3083,101.0,1
135339,09:05:14,17,00171001,996115,3083,Frascati Road,0.0,431,117.0,1
135340,09:07:11,17,00171001,996115,431,Mount Merrion Ave,0.0,432,61.0,1
135341,09:08:12,17,00171001,996115,432,Mount Merrion Ave,0.0,876,1180.0,1
135342,09:27:52,17,00171001,996115,876,Bird Avenue,0.0,1315,359.0,1
135343,09:33:51,17,00171001,996115,1315,Nutgrove Ave,0.0,1330,220.0,1
135344,09:37:31,17,00171001,996115,1330,Grange Road,0.0,1086,281.0,1
135345,09:42:12,17,00171001,996115,1086,Terenure Rd West,0.0,3362,721.0,1
135346,20:02:42,27,077A0001,999390,396,Pearse Street,0.0,398,100.0,1
135347,20:04:22,27,077A0001,999390,398,Pearse Street,0.0,400,141.0,1
135348,20:06:43,27,077A0001,999390,400,Pearse Street,0.0,4522,200.0,1
135349,20:10:03,27,077A0001,999390,4522,College Green,0.0,1934,239.0,1
135350,20:14:02,27,077A0001,999390,1934,Dame Street,0.0,2310,121.0,1
135351,20:16:03,27,077A0001,999390,2310,Werburgh Street,0.0,2315,300.0,1
135352,20:21:03,27,077A0001,999390,2315,Cork Street,0.0,2094,59.0,1
135353,20:22:02,27,077A0001,999390,2094,Cork Street,0.0,2095,200.0,1
135354,20:25:22,27,077A0001,999390,2095,Crumlin Road,0.0,5133,700.0,1
135355,20:37:02,27,077A0001,999390,5133,Tymon Park Rd,0.0,2616,367.0,1
135356,20:43:09,27,077A0001,999390,2616,Old Bawn Rd,0.0,4347,259.0,1
135357,20:47:28,27,077A0001,999390,4347,Old Blessington Rd,0.0,2560,260.0,1

# Make Model For Address DF With StatsModels

In [37]:
# Import package matplotlib for visualisation/plotting
import matplotlib.pyplot as plt
import matplotlib as mpl

# this is the standard import if you're using "formula notation" (similar to R)
import statsmodels.formula.api as smf

#For showing plots directly in the notebook
%matplotlib inline

In [38]:
# create a fitted model with the features selected from exercise 1
lm = smf.ols(formula='travelTime ~ LineId + Address + dstAddress + TimeStamp + Rain + weekday', data = stop_df).fit()

In [40]:
# Make small test
X_new = pd.DataFrame({'LineId': [145], 'Address':['Bray Road'],'dstAddress':['Shankill'], 'TimeStamp': ["10:00:05"], 'Rain':[0.0],'weekday':[1]})
X_new.head()

     Address  LineId  Rain TimeStamp dstAddress  weekday
0  Bray Road     145   0.0  10:00:05   Shankill        1

In [41]:
# Predicted time of model
lm.predict(X_new)

array([ 320.])